<a href="https://colab.research.google.com/github/Akshayb2003/numpy/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #numerical python

#array collection of data with same data type(Homogeneous)


a=np.array([1,2,3.0,4,"a"])
print(a)

['1' '2' '3.0' '4' 'a']


In [ ]:
#slicing forward slicing backward slicing

b=np.array([1,2,3,4,5])

#print 1,2
print(b[0:2])
#print 5,4
print(b[-1:-3:-1])
#print 4,5
print(b[3:])

#print 2,1
print(b[-4::-1])

[1 2]
[5 4]
[4 5]
[2 1]


In [ ]:
#dimension
a=np.array([0,2,3,4,5])
b=np.array([[1,2],[3,4]])

a.ndim  #diamension=1 vector

b.ndim #dimension =2 matrix

print(b)

b.shape #to know the shape ie number of rows and colums

[[1 2]
 [3 4]]


(2, 2)

In [ ]:
#create a 2x2 matrix 2,3,4,5
a=np.array([[2,3],[4,5]])
print(a)
print(a.shape)
print(a.ndim)


print(a.size) #number of elements in a mtrix

[[2 3]
 [4 5]]
(2, 2)
2
4


In [ ]:
#craete a 2x3 matrix and print the size shape and dimension
a=np.array([[1,2,3],[4,5,6]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2 3]
 [4 5 6]]
6
(2, 3)
2


In [ ]:
#create a 4x2 matrix display its size shape dimension


a=np.array([[1,2],[3,4],[5,6],[6,7]])
print(a)
print(a.size)
print(a.shape)
print(a.ndim)

[[1 2]
 [3 4]
 [5 6]
 [6 7]]
8
(4, 2)
2


In [ ]:
a=np.array([[1,2,4,5],[3,4,
5,7],[5,6,7,8],[6,7,9,10]])
print(a)
print(a.size)
print(a.shape)

[[ 1  2  4  5]
 [ 3  4  5  7]
 [ 5  6  7  8]
 [ 6  7  9 10]]
16
(4, 4)


In [ ]:
z=np.array([[1,2,4,5],[3,4,
5,7],[5,6,7,8],[6,7,9,10]])


z[0]

z[:,0]

z[1,1]

z[2,2]

z[3,2:]

z[2:,2:]

z[:0,3:]
print(z)

[[ 1  2  4  5]
 [ 3  4  5  7]
 [ 5  6  7  8]
 [ 6  7  9 10]]


In [ ]:
#zero matrix
z=np.array


z=np.zeros([3,3,3],dtype=complex)  #dtype=int
print(z)

[[[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]

 [[0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]
  [0.+0.j 0.+0.j 0.+0.j]]]


In [ ]:
#one matrix
z=np.ones([3,3],dtype=int)
print(z)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
#create two 2x2 mtrix
a=np.array([[1,2],[3,4]])
b=np.array([[3,1],[6,7]])
print(a)
print(b)

[[1 2]
 [3 4]]
[[3 1]
 [6 7]]


In [ ]:
#matrix addition
print(a+b)


#matrix substraction
print(a-b)




#matrix multiplication
#print(a*b) is not a matrix maultiplication
print(a@b)
print(a.dot(b))





#matrix division
print(a/b)













 # magic __add__

[[ 4  3]
 [ 9 11]]
[[-2  1]
 [-3 -3]]
[[15 15]
 [33 31]]
[[15 15]
 [33 31]]
[[0.33333333 2.        ]
 [0.5        0.57142857]]


In [ ]:
#full matrix


z=np.full([3,3],5,dtype=int)
print(z)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#create 3x4 matrix with value 9 and a datatype complex
a=np.full([3,4],9,dtype=complex)
print(a)

[[9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]
 [9.+0.j 9.+0.j 9.+0.j 9.+0.j]]


In [ ]:
#identity matrix
z=np.identity(3)
print(z)

#z=np.eye(3)
#z


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create a 4x4 matrix
y=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(y)
print(y.size)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
16


In [ ]:
a=y.reshape(8,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16]])

In [ ]:
#arange
a=np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

In [ ]:
#create a 5x2 matrix using arange
a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
#create a 3x3 matrix with float values
a=np.array([[2.5,3.6,3.5],[1.5,1.1,6.5],[7.1,2.5,7.1]])
a

array([[2.5, 3.6, 3.5],
       [1.5, 1.1, 6.5],
       [7.1, 2.5, 7.1]])

In [ ]:
#floor
z=np.floor(a)
z

array([[2., 3., 3.],
       [1., 1., 6.],
       [7., 2., 7.]])

In [ ]:
#ceil
z=np.ceil(a)
z

array([[3., 4., 4.],
       [2., 2., 7.],
       [8., 3., 8.]])

In [ ]:
#round
z=np.round(a)
z

array([[2., 4., 4.],
       [2., 1., 6.],
       [7., 2., 7.]])

In [ ]:
#create 3x3 matrix

a=np.arange(1,10).reshape(3,3)
print(a)

a.max()

a.max(axis=1)
a.max(axis=1)
a.min(axis=1)
a.min(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

22-09-25

In [36]:
#flatten
a.flatten()   #to convert into a one dimensional array

array([3, 4, 1, 5, 3, 1, 6, 9, 8])

In [ ]:
#sorting
#craete 3x3 matrix
a=np.array([[3,4,1],[5,3,1],[6,9,8]])
print(a)
b=np.sort(a,axis=0)
print(b)
c=np.argsort(a,axis=1)       #sort on basis of index
print(c)

[[3 4 1]
 [5 3 1]
 [6 9 8]]
[[3 3 1]
 [5 4 1]
 [6 9 8]]
[[2 0 1]
 [2 1 0]
 [0 2 1]]
